title:              PiParadox
email:              ankita.piparadox@gmail.com
description:        "India's Own Math's Teacher"
author:             Team PiParadox
baseurl:            ""
url:                "http://mathinfo.piparadox.live/"

# Social Profiles
twitter_username:   PiParadox1
#github_username:    BlackrockDigital
facebook_username:  ThePiParadox
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
